### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by asahinobori** [DNNDHH/FGO-ADET#2]
![FGO-ADET_not_work](https://github.com/DNNDHH/FGO-ADET/assets/3366004/e2ba6269-d855-4fff-a5fd-e88efcec8775)
follow your steps and decrypt, show this error message, follow the message and create an empty key_o.txt，not work

**Comment by DNNDHH** [comment]
Oh…I forgot to update the pop-up window information…You should directly copy the 54cc…file into the program directory! Click decrypt…it will automatically parse and decrypt! It is normal…I will update the pop-up window text description later🤣

**Comment by DNNDHH** [comment]
不对啊～我看你54cc文件在目录中了…怎么会出现这个报错😳54cc文件没改过什么吧

**Comment by DNNDHH** [comment]
https://github.com/DNNDHH/FGO-ADET/releases/tag/v4.0 下最新的zip！你的程序怎么有20MB，最新15.8MB啊，你可能下了旧版本！

**Comment by asahinobori** [comment]
FGO-ADET-4.0失败了，再试FGO-ADET-3.0，还是这个错误，上图是用3.0截图的，可能是环境的问题？
我换个环境再测试一下

**Comment by asahinobori** [comment]
我的54cc...文件里的内容首部有不可见字符导致的🤣，删除掉后你的程序正常运行了，感谢回复，nice
![FGO-ADET_not_work_2](https://github.com/DNNDHH/FGO-ADET/assets/3366004/47e33120-c32e-4c0d-9c0c-2b17dc281ada)

**Comment by DNNDHH** [comment]
😅等等…ec01？你绑定过 ANIPLEX 账号？

**Comment by asahinobori** [comment]
没有呢，我这几天才知道有什么 ANIPLEX 账号，还没绑定呢，可能我的号很老以前的账号吧，一直都有这个不可见字符在首部，以前用 https://github.com/hexstr/FGODailyBonus 看说明也是说 从字母Z复制到结尾 ，即忽略前面的东西，用你这个程序，以为可以傻瓜一点不用变更文件😅

**Comment by DNNDHH** [comment]
😅一般来说是FC01开头…待会更新一下程序添加EC01开头支持

**Comment by asahinobori** [comment]
> 😅一般来说是FC01开头…待会更新一下程序添加EC01开头支持

要不直接从文件头开始找 0x5a 即'Z' 作为数据头，可能会好一点，不保证还有其它首部

**Comment by DNNDHH** [comment]
> > 😅一般来说是FC01开头…待会更新一下程序添加EC01开头支持
> 
> 要不直接从文件头开始找 0x5a 即'Z' 作为数据头，可能会好一点，不保证还有其它首部

😂我怎么没想到…这个好
